aurelia/ux

- src/button/ux-button-theme.css
- src/colors/shadows.ts
- src/designs/ios-design.ts
- src/designs/material-design.ts
- src/index.ts
- src/styles/style-factory.ts
Added box-shadow shadow/elevation design resources, updated the material-design and ios-design themes to include references to these new resources so they can be applied using the $design. notation in component themes. 
Updated the ux-button theme to use the new shadow styles and added a new style to the button for the :focus state.
> Material Design shadows

- .vscode/settings.json
- src/button/ux-button-theme.css
- src/form/ux-field-theme.css
- src/form/ux-field-theme.ts
- src/form/ux-field.html
- src/form/ux-field.ts
- src/form/ux-form-theme.css
- src/form/ux-form-theme.ts
- src/form/ux-form.html
- src/form/ux-form.ts
- src/form/ux-submit-attribute.ts
- src/index.ts
- src/input-info/ux-input-info-theme.css
- src/input-info/ux-input-info.html
- src/input-info/ux-input-info.ts
- src/input/ux-input-theme.css
- src/textarea/ux-textarea-theme.css
Add ux-form component and ux-field component to help with label positioning and form layouts.
Styling
- `.form-row` class to handle a row of fields
- `ux-field` component to handle labels and label positioning
- adding a `label` attribute with a value on the `ux-field` component will cause it to create a label if none exist already.
Submit
You can `submit.delegate="methodName()"` to catch a submit event in the form. This is not a required way of using the form and it can be used purely for styling purposes if one would desire to do so.
- ux-submit attribute, allowing buttons to trigger a submit function (not required to use the form)
- method on the form `submitForm` to trigger a submit event
- adding `submit-on-enter` will force the form as a whole to capture enter keyups triggering the …
> feat(form): add form layout and labels

- src/chip-input/ux-chip-input-theme.css
- src/chip-input/ux-chip-input-theme.ts
- src/chip-input/ux-chip-input.html
- src/chip-input/ux-chip-input.ts
- src/chip-input/ux-chip-theme.css
- src/chip-input/ux-chip-theme.ts
- src/chip-input/ux-chip.html
- src/chip-input/ux-chip.ts
- src/chip-input/ux-tag-theme.css
- src/chip-input/ux-tag-theme.ts
- src/chip-input/ux-tag.html
- src/chip-input/ux-tag.ts
- src/index.ts
Add Material Design chips, a chip editor, and smaller tags.
Usage
``` html
<ux-chip-input value.bind="commaDelimitedString"></ux-chip-input>
<ux-chip-input separator="\;/" value.bind="customDelimitedString"></ux-chip-input>
<ux-chip-input chip-array.bind="arrayValue"></ux-chip-input>
<ux-tag repeat.for="keyword of Keywords">${keyword}</ux-tag>
<ux-tag repeat.for="keyword of Keywords" deletable close.trigger="closingChip()">${keyword}</ux-tag>
<ux-chip repeat.for="keyword of Keywords">${keyword}</ux-chip>
<ux-chip repeat.for="keyword of Keywords" deletable close.trigger="closingChip()">${keyword}</ux-chip>
```
Editor
- remove chip from list
- add chip to list
- double click to edit any chip
- left arrow on empty input to edit newest chip
- enter or tab to add a chip
Chip
- Material Design …
> feat(chips): add material chips

- src/input-info/ux-input-info-theme.css
hides all hint-text and error-text except the first child. resolves an issue where multiple error messages can display at once
> style(input-info): change error display

- src/index.ts
For webpack (and other static loader) compatibility.
> Wrap module references in PLATFORM.moduleName.

- src/checkbox/ux-checkbox.ts
set value to null and check for null instead of only typeof !== 'boolean' to prevent errors stemming from value being set to an undefined value
set checked to null instead of using delete since delete will not work in this instance and it is better to set to null
> fix(checkbox): fix delete this.checked issue

- src/button/ux-button-theme.css
- src/button/ux-button.ts
this adds in disabled behavior when defined for `<ux-button></ux-button>`
resolves #75
> fix(button): add disable button behavior

- src/checkbox/ux-checkbox-theme.css
- src/checkbox/ux-checkbox.ts
this fixes disabled behavior when defined for `<ux-checkbox></ux-checkbox>`
resolves #79
> fix(checkbox) disabled checkbox behavior

- packages/checkbox/src/ux-checkbox.ts
- packages/input/src/ux-input.ts
- packages/radio/src/ux-radio.ts
- packages/switch/src/ux-switch.ts
- packages/textarea/src/ux-textarea.ts
There were issues with removing event of native inputs during unbind, which would be a bit late. I'm not sure what caused the issue but moving them to `attached` and `detached` can help avoid that.
> fix: change event surpress timing

- package-lock.json
The outdated package-lock.json ensures a non-working environment when doing `npm install` after a clean clone. Workarounds are either delete it first, or use yarn.
Might as well update it so that when people clone this repo, `npm install` will just work?
> fix(package-lock.json): update package-lock to get a working env after npm install

- packages/button/src/ux-button.css
- packages/checkbox/src/ux-checkbox.css
- packages/chip-input/src/ux-chip-input.css
- packages/chip-input/src/ux-chip.css
- packages/chip-input/src/ux-tag.css
- packages/datepicker/src/ux-calendar.css
- packages/datepicker/src/ux-datepicker.css
- packages/datepicker/src/ux-picker-dialog.css
- packages/datepicker/src/ux-year-list.css
- packages/form/src/ux-form.css
- packages/grid/src/ux-grid.css
- packages/icons/src/ux-icon.css
- packages/input-info/src/ux-input-info.css
- packages/input/src/ux-input.css
- packages/list/src/ux-list.css
- packages/radio/src/ux-radio.css
- packages/switch/src/ux-switch.css
- packages/textarea/src/ux-textarea.css
Partial fix for #149.
It adds fallback properties for css properties which have a default set like `var(--x, default)`. No fallbacks where added for `var(--x)` calls.
Adding fallbacks for the css `var(...)` references in the `.ts` files is still missing. Cleanest solution to also fix those is to have/use something like `PAL.Supports.cssVariables` to determine support at runtime.
> feat(css): add fallback properties to CSS

- packages/datepicker/src/ux-datepicker.ts
```ts
export class ViewModel {
birthday = new Date('2017-03-02');
}
```
```html
<ux-datepicker value.bind="birthday"></ux-datepicker>
```
At the moment, the datepicker's textbox stays empty, while it should display the selected date.
This fix makes sure the textbox is properly initialized when `value` is bound to an actual `Date`.
> fix(datepicker): call valueChanged on bind to initialize textbox value

- packages/components/src/index.ts
Fixes #233 
I've included another fix, [exposing all (*) variables from components](https://github.com/aurelia/ux/commit/50e70ee0b0c054e8189fe44c903651cc8931f711). I don't see a reason why we would not expose all the variables exposed from the components themselves. But maybe I missed something. Let me know.
> fix(components): components registration

- packages/core/src/components/ux-choice-container-attribute.ts
Here is a fix for `ux-choice-container` attribute. When we optimized the code in `valueChanged()` we removed an important part... this valueChanged() must also request to process the value if the `newValue` is different thant `oldValue`.
Currently the attribute works well for one-way binding because the right choice is selected anyway. But for two-way binding the valueChanged() needs to process the value.
Ready for review @EisenbergEffect @bigopon
> fix(choice): process value change is new !== old

- packages/chip-input/src/ux-chip-input.ts
I noticed that when using a `chip-input` inside a drawer we get a undesired behavior. Both are listening for the keyup change on ENTER and ESC keys.
I suggest that when the chip-input detects the ENTER or ESC keyup it stops the propagation so that other handlers don't act on it as well.
@bigopon what do you think ?
> fix(chip-input): stop propagation on ENTER or ESC

- packages/core/src/components/ux-input-component.ts
- packages/core/src/index.ts
- packages/input/src/index.ts
- packages/input/src/ux-default-input-configuration.ts
- packages/input/src/ux-input.ts
Returning true is needed to support clicks on a native calendar button.
> fix(input): pass through date input types, default config

- packages/select/src/ux-select-theme.ts
- packages/select/src/ux-select.ts
The component might be themed globally in which case `theme` field won't have the actual value.
Plus, number does not work with CSS, it needs to have 'ms'.
> fix(select): apply initial theme value, fix transition

- packages/core/src/components/ux-input-component.css
In outline mode, the "border" element takes the full height of the component. In such scenario it is positioned "above" potential leading and trailing icons and prevents these icons to receive any clicks.
By ignore pointer events on the border element we let the click go through and reach the leading and trailing icons.
> fix(core): ignore pointer-events on components borders

- packages/lookup/src/ux-lookup.ts
it's a useful feature when a number of options is limited and a user wants to see them before filtering
> feat(lookup): allow preloading options

- packages/datepicker/src/ux-calendar.ts
Currently the weekdays in the calendar always start on Sunday. However this is a locale specific thing and we should call `weekdays(true)` in order to follow locale in used by moment.
See https://stackoverflow.com/questions/43520233 for more infos.
> Fix(datepicker): respect locale specific order for weekdays

- packages/core/src/components/ux-input-component.css
When an input field has no value, without this fix the input textbox is displayed with a background color and overflow the ux-input wrapper.
This fix hide the input textbox for disabled empty fields, leaving only the label in position.
Naturally the textbox is displayed for non-empty fields.
> fix(input): disabled styles for input component
