aurelia/ux

src/colors/swatches.ts
change lgithBlue to lightBlue
closes #37
=> fix(swatches): fix color name typo

src/aurelia-ux.ts, src/designs/design-attributes.ts, src/effects/element-rect.ts, src/effects/paper-ripple.ts, src/effects/paper-wave.ts, src/hosts/cordova.ts, src/hosts/electron.ts, src/index.ts, src/input/ux-input.ts, src/styles/style-compiler.ts, src/styles/style-controller.ts, src/styles/style-engine.ts, src/styles/style-factory.ts, src/styles/style-locator.ts, src/styles/style-resource.ts, src/styles/style-strategy.ts, src/textarea/ux-textarea.ts, src/ux-configuration.ts, tslint.json
Most changes were of the following variety:
* change `let` to `const`
* change casting with `<>` to `as`
* change `Object` param type to `object`
fixes #43
=> refactor(all): refactor for lint tests

src/input/ux-input.html, src/input/ux-input.ts
add the following input types: 
* email
* url
* tel
* search
resolves: #45
=> feat(input): add input types

README.md
=> Update development script

src/index.ts
expose style engine and themable to allow creation of custom components
based on aurelia ux
resolves #73
=> feat(ux): expose style engine

src/checkbox/ux-checkbox.ts
Adds the capability to assign a value to the checkbox components unchecked state.
resolves #69
=> feat(checkbox): add unchecked value

src/checkbox/ux-checkbox.html, src/checkbox/ux-checkbox.ts, src/form/ux-form.ts
=> fix(checkbox | form): label for and form submit

packages/button/src/ux-button.css, packages/checkbox/src/ux-checkbox.css, packages/checkbox/src/ux-checkbox.html, packages/checkbox/src/ux-checkbox.ts, packages/textarea/src/ux-textarea.css
Resolves several issues:
* Button sizing issue ( #103 )
* Textarea sizing issue ( #105 )
* Checkbox check centering issue
Adds the following functionality:
* Checkbox now toggles state when the spacebar is pressed ( #100 )
=> Style Changes

packages/boilerplate/.npmignore, packages/boilerplate/README.md, packages/boilerplate/package.json, packages/boilerplate/src/index.ts, packages/boilerplate/src/ux-boilerplate-theme.ts, packages/boilerplate/src/ux-boilerplate.css, packages/boilerplate/src/ux-boilerplate.html, packages/boilerplate/src/ux-boilerplate.ts, packages/boilerplate/tsconfig.json, packages/radio/.npmignore, packages/radio/package-lock.json, packages/radio/package.json, packages/radio/src/index.ts, packages/radio/src/ux-radio-theme.ts, packages/radio/src/ux-radio.css, packages/radio/src/ux-radio.html, packages/radio/src/ux-radio.ts, packages/radio/tsconfig.json
Adds a component boilerplate for creating new components quickly complete with a readme
Adds a new component, the radio button
=> Component Boilerplate and Radio Component

packages/datepicker/src/ux-datepicker.html
template tag was not closed
resolves #111
=> fix(datepicker): fix invalid html template

packages/icons/src/ux-icon.css
use css variable defined by size property from theme to set width and
height
resolves #116
=> fix(icons): fix icon styles to use size variable

packages/icons/src/ux-icon.html
allows custom svg icon to be set as a content
resolves #118
=> feat(icons): add slot element

lerna.json, packages/components/src/index.ts, packages/switch/.npmignore, packages/switch/package-lock.json, packages/switch/package.json, packages/switch/src/index.ts, packages/switch/src/ux-switch-theme.ts, packages/switch/src/ux-switch.css, packages/switch/src/ux-switch.html, packages/switch/src/ux-switch.ts, packages/switch/tsconfig.json, packages/switch/tslint.json, tsconfig.json
Add a switch component for Aurelia UX
```html
<ux-switch checked.bind="booleanValue"></ux-switch>
```
=> feat(switch): Add switch component

README.md
Temporary playground to demo for feature request/ bugs and new feature developments
=> Add online playground link

karma.conf.js, package-lock.json, package.json, packages/core/.npmignore, packages/core/src/aurelia-ux.ts, packages/core/src/designs/design-processor.ts, packages/core/src/index.ts, packages/core/src/reset.css, packages/core/src/styles/global-style-engine.ts, packages/core/src/styles/global-style.ts, packages/core/src/styles/style-controller.ts, packages/core/src/ux-configuration.ts, packages/core/tsconfig.json, test/main.ts, test/unit/aurelia-ux.spec.ts, test/unit/global-style-engine.spec.ts, tsconfig.json
Adds reset css code to the header of the document
when aurelia-ux is started. This can be disabled in the configuration.
combines all css variables into a single style element
=> Add css reset and global style controller

packages/checkbox/src/index.ts, packages/radio/src/ux-radio.css, packages/select/package.json, packages/select/src/ux-select.ts
fixes #154 
fixes #155
@ZHollingshead Copy paste got me. Forgot to copy-paste radio css though
=> fix(Select, Radio, Checkbox): fix issues from #86a4e3

packages/select/src/ux-optgroup.ts, packages/select/src/ux-option.ts, packages/select/src/ux-select.ts
=> fix(Select): use conventional view strategy

package.json, packages/boilerplate/package.json, packages/button/package.json, packages/checkbox/package.json, packages/chip-input/package.json, packages/components/package.json, packages/core/package.json, packages/datepicker/package.json, packages/form/package.json, packages/grid/package.json, packages/icons/package.json, packages/input-info/package.json, packages/input/package.json, packages/list/package.json, packages/radio/package.json, packages/select/package.json, packages/switch/package.json, packages/textarea/package.json
@EisenbergEffect @bigopon 
(no idea what's up with all the blank +/- on this one.. might be line endings related)
=> chore(all): update aurelia-binding dependency

README.md
npm badge should point to new lerna package
=> doc(readme): fixed npm badge

packages/chip-input/src/ux-chip-input.html, packages/input/src/ux-input.html
ref https://github.com/aurelia/templating/pull/647#issuecomment-427989601
=> fix: fix html5 syntax

packages/switch/src/ux-switch.html
=> fix(switch): wrong aria attribute

packages/icons/src/ux-icon.ts
For when a size is provided but no theme
=> fix(icon): avoid unset theme property

packages/form/src/index.ts, packages/form/src/ux-submit-attribute.ts
=> fix(form): properly register the submit attribute

app/src/main.ts, app/src/positioning.css, app/src/positioning.html, app/src/positioning.ts, app/src/routes.ts, app/webpack.config.js, lerna.json, packages/positioning/.npmignore, packages/positioning/.npmrc, packages/positioning/karma.conf.ts, packages/positioning/package-lock.json, packages/positioning/package.json, packages/positioning/src/index.ts, packages/positioning/src/interfaces.ts, packages/positioning/src/ux-positioning.css, packages/positioning/src/ux-positioning.ts, packages/positioning/test/setup.ts, packages/positioning/test/unit/index.spec.ts, packages/positioning/tsconfig-test.json, packages/positioning/tsconfig.json
New positioning package following on #246 discussion.
I've set the constructor to work with `Factory.of()` and I provide a `UxPositioningFactory` type for better typescript support. Then usage will be (as can be found in demo):
```ts
import { UxPositioning, UxPositioningFactory } from '@aurelia-ux/positioning';
@inject(Factory.of(UxPositioning))
export class SomeElement {
private anchor: HTMLElement;
private element: HTMLElement;
private positioning: UxPositioning;
constructor(private positioningFactory: UxPositioningFactory) {
}
public someMethod() {
this.positioning = this.positioningFactory(this.anchor, this.element, {
placement: 'bottom'
});
}
}
@bigopon @EisenbergEffect This package is ready for final review. When merged I will immediately use it for the modal package.
=> Positioning

packages/slider/src/ux-slider.html, packages/slider/src/ux-slider.ts
* https://github.com/aurelia/ux/commit/d7fdf8d4938bd5810e0f878b9c696a2fd5e60eac : fixes the touch handler
* https://github.com/aurelia/ux/commit/d9db80cfc5fa2e5b110dff786cb68620b2c62850 : fixes the position of the slider when the component has leading and/or trailing icons. 
@bigopon ready for review/merge
=> fix(slider): touch start handling and mouse slider normalized correctly

packages/checkbox/src/ux-checkbox.css
offset = 24px + (50px - 24px)/2 = 37px
=> fix(checkbox): center ripple container

packages/button/src/ux-button.css
=> fix(button): don't allow clicks on disabled buttons

packages/lookup/src/ux-lookup-theme.ts, packages/lookup/src/ux-lookup.css, packages/lookup/src/ux-lookup.html, packages/lookup/src/ux-lookup.scss, packages/lookup/src/ux-lookup.ts
Also fix closing animation.
Fixes a bug when the list is invisible but still clickable
=> fix(lookup): hide transparent list

app/src/app.css, app/src/showcase.html, app/webpack.config.js, packages/lookup/src/ux-lookup.css, packages/lookup/src/ux-lookup.scss, packages/select/src/ux-select.ts
This fixes an issue with parents which might have hidden overflow
Also, clean up lookup animation
=> fix(select): move dropdown to body

app/package.json, app/src/components.html, app/src/main.ts, app/webpack.config.js, lerna.json, packages/__tests__/karma.conf.js, packages/__tests__/test/input.integration.spec.ts, packages/__tests__/test/popup.integration.spec.ts, packages/__tests__/test/tree-view.integration.spec.ts, packages/__tests__/util.ts, packages/components/package.json, packages/components/src/index.ts, packages/core/src/styles/style-engine.ts, packages/popup/.npmignore, packages/popup/.npmrc, packages/popup/karma.conf.js, packages/popup/package.json, packages/popup/rollup.config.js, packages/popup/src/index.ts, packages/popup/src/ux-popup-theme.ts, packages/popup/src/ux-popup.css, packages/popup/src/ux-popup.html, packages/popup/src/ux-popup.scss, packages/popup/src/ux-popup.ts, packages/popup/test/popup.spec.ts, packages/popup/test/setup.ts, packages/popup/tsconfig-test.json, packages/popup/tsconfig.build.json, packages/popup/tsconfig.json
=> feat(popup): add popup

app/src/components.html, packages/expandable/src/ux-expandable.css, packages/expandable/src/ux-expandable.html, packages/expandable/src/ux-expandable.scss, packages/expandable/src/ux-expandable.ts
Not sure why I had it so complex in the first place.
Plus allow specifying an accordion group id,
=> feat(expandable): allow specifying an accordion group id
